name: build

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - uses: CultureHQ/actions-yarn@v1.0.1

    - run: yarn
    - run: node ./scripts/getStoriesList.js
    - run: yarn eslint .
    - run: yarn flow
    - run: yarn jest
    - run: yarn build
    - run: yarn website:build

    - name: Install Surge
      run: npm install -g surge

    - name: Deploy to Surge
      run:  surge ./website https://startown.surge.sh/ --token ${{secrets.SURGE}}
